



// CHECK IF USER IS AUTHORIZED

// CHECK IF USER IS ALLOWED TO ACCESS THAT FILES VIA ITS FILEID

// GET FILE URL using the imported amplify function getUrl

// FETCH FILE FROM AMPLIFY URL

// RETURN JSON CONTAINING THE FILES CONTENT AS A STRING

